"""SINGLE source for all 干支/五行 constant tables (eng review 3A).

Every other engine module imports from here. One test (tests/test_wuxing.py)
validates the full tables against hand-checked classical references.
"""

STEMS = "甲乙丙丁戊己庚辛壬癸"
BRANCHES = "子丑寅卯辰巳午未申酉戌亥"

WOOD, FIRE, EARTH, METAL, WATER = "木", "火", "土", "金", "水"
ELEMENTS = [WOOD, FIRE, EARTH, METAL, WATER]

STEM_ELEMENT = {
    "甲": WOOD, "乙": WOOD,
    "丙": FIRE, "丁": FIRE,
    "戊": EARTH, "己": EARTH,
    "庚": METAL, "辛": METAL,
    "壬": WATER, "癸": WATER,
}
STEM_YANG = {s: i % 2 == 0 for i, s in enumerate(STEMS)}  # 甲丙戊庚壬 yang

BRANCH_ELEMENT = {
    "子": WATER, "丑": EARTH, "寅": WOOD, "卯": WOOD, "辰": EARTH, "巳": FIRE,
    "午": FIRE, "未": EARTH, "申": METAL, "酉": METAL, "戌": EARTH, "亥": WATER,
}
BRANCH_YANG = {b: i % 2 == 0 for i, b in enumerate(BRANCHES)}  # 子寅辰午申戌 yang

# 支藏干 — hidden stems, main qi first
HIDDEN_STEMS = {
    "子": ["癸"], "丑": ["己", "癸", "辛"], "寅": ["甲", "丙", "戊"], "卯": ["乙"],
    "辰": ["戊", "乙", "癸"], "巳": ["丙", "庚", "戊"], "午": ["丁", "己"],
    "未": ["己", "丁", "乙"], "申": ["庚", "壬", "戊"], "酉": ["辛"],
    "戌": ["戊", "辛", "丁"], "亥": ["壬", "甲"],
}

# 生 cycle: X generates SHENG[X];  剋 cycle: X controls KE[X]
SHENG = {WOOD: FIRE, FIRE: EARTH, EARTH: METAL, METAL: WATER, WATER: WOOD}
KE = {WOOD: EARTH, EARTH: WATER, WATER: FIRE, FIRE: METAL, METAL: WOOD}
SHENG_REV = {v: k for k, v in SHENG.items()}  # X is generated by SHENG_REV[X]

LIUCHONG = [("子", "午"), ("丑", "未"), ("寅", "申"), ("卯", "酉"), ("辰", "戌"), ("巳", "亥")]
LIUHE = [("子", "丑"), ("寅", "亥"), ("卯", "戌"), ("辰", "酉"), ("巳", "申"), ("午", "未")]
LIUHAI = [("子", "未"), ("丑", "午"), ("寅", "巳"), ("卯", "辰"), ("申", "亥"), ("酉", "戌")]
SANHE = [(("申", "子", "辰"), WATER), (("寅", "午", "戌"), FIRE),
         (("巳", "酉", "丑"), METAL), (("亥", "卯", "未"), WOOD)]

CHONG_MAP = {a: b for pair in LIUCHONG for a, b in (pair, pair[::-1])}
HE_MAP = {a: b for pair in LIUHE for a, b in (pair, pair[::-1])}
HAI_MAP = {a: b for pair in LIUHAI for a, b in (pair, pair[::-1])}

ELEMENT_COLOURS = {
    WOOD: ["綠", "青"], FIRE: ["紅", "紫"], EARTH: ["黃", "棕"],
    METAL: ["白", "金"], WATER: ["黑", "藍"],
}
ELEMENT_EN = {WOOD: "Wood", FIRE: "Fire", EARTH: "Earth", METAL: "Metal", WATER: "Water"}

# 洛書 palaces: number, direction, element, trigram lines (bottom, mid, top; 1=yang)
PALACES = {
    "坎": {"num": 1, "dir": "N",  "element": WATER, "lines": (0, 1, 0)},
    "坤": {"num": 2, "dir": "SW", "element": EARTH, "lines": (0, 0, 0)},
    "震": {"num": 3, "dir": "E",  "element": WOOD,  "lines": (1, 0, 0)},
    "巽": {"num": 4, "dir": "SE", "element": WOOD,  "lines": (0, 1, 1)},
    "乾": {"num": 6, "dir": "NW", "element": METAL, "lines": (1, 1, 1)},
    "兌": {"num": 7, "dir": "W",  "element": METAL, "lines": (1, 1, 0)},
    "艮": {"num": 8, "dir": "NE", "element": EARTH, "lines": (0, 0, 1)},
    "離": {"num": 9, "dir": "S",  "element": FIRE,  "lines": (1, 0, 1)},
}
NUM_TO_PALACE = {v["num"]: k for k, v in PALACES.items()}
DIR_TO_PALACE = {v["dir"]: k for k, v in PALACES.items()}
CENTER_ELEMENT = EARTH  # 中宮 5

# Star number → element (九星五行)
STAR_ELEMENT = {1: WATER, 2: EARTH, 3: WOOD, 4: WOOD, 5: EARTH,
                6: METAL, 7: METAL, 8: EARTH, 9: FIRE}

# Forward flight path: order palaces are visited flying from the center (洛書軌跡)
FLIGHT_ORDER = ["中", "乾", "兌", "艮", "離", "坎", "坤", "震", "巽"]

# 24 mountains per palace in (地元, 天元, 人元) order with yin/yang polarity.
# True = yang (順飛), False = yin (逆飛).
MOUNTAINS = {
    "坎": [("壬", True), ("子", False), ("癸", False)],
    "艮": [("丑", False), ("艮", True), ("寅", True)],
    "震": [("甲", True), ("卯", False), ("乙", False)],
    "巽": [("辰", False), ("巽", True), ("巳", True)],
    "離": [("丙", True), ("午", False), ("丁", False)],
    "坤": [("未", False), ("坤", True), ("申", True)],
    "兌": [("庚", True), ("酉", False), ("辛", False)],
    "乾": [("戌", False), ("乾", True), ("亥", True)],
}
# Compass: mountain centre bearings, 15° each. 子 = 0° (N), clockwise.
MOUNTAIN_ORDER = ["子", "癸", "丑", "艮", "寅", "甲", "卯", "乙", "辰", "巽", "巳", "丙",
                  "午", "丁", "未", "坤", "申", "庚", "酉", "辛", "戌", "乾", "亥", "壬"]
OPPOSITE_MOUNTAIN = {m: MOUNTAIN_ORDER[(i + 12) % 24] for i, m in enumerate(MOUNTAIN_ORDER)}


def mountain_of_degrees(deg: float) -> str:
    """Facing bearing in degrees (0=N, clockwise) → 24-mountain name."""
    idx = int(((deg + 7.5) % 360) // 15)
    return MOUNTAIN_ORDER[idx]


def mountain_palace(mountain: str) -> str:
    for palace, ms in MOUNTAINS.items():
        if any(m == mountain for m, _ in ms):
            return palace
    raise ValueError(f"unknown mountain {mountain}")


def mountain_yuan(mountain: str) -> int:
    """0=地元, 1=天元, 2=人元."""
    for ms in MOUNTAINS.values():
        for i, (m, _) in enumerate(ms):
            if m == mountain:
                return i
    raise ValueError(f"unknown mountain {mountain}")
