/* GENERATED by scripts/glossary_js.py — do not edit by hand. */
(function () {
  "use strict";
  if (window.__glTip) return;
  window.__glTip = 1;
  var st = document.createElement("style");
  st.textContent = ":root{--wood:#187a35;--fire:#c5221f;--earth:#8a6d1f;--metal:#8a6500;--water:#1a56b0}.el-wood{color:var(--wood)}.el-fire{color:var(--fire)}.el-earth{color:var(--earth)}.el-metal{color:var(--metal)}.el-water{color:var(--water)}.zh[data-tip]{cursor:help;text-decoration:underline dotted;text-decoration-thickness:1px;text-underline-offset:3px;border-radius:2px}.zh[data-tip]:focus-visible{outline:2px solid #8a6d1f;outline-offset:2px}.gl-tip{position:fixed;z-index:9999;max-width:calc(100vw - 32px);width:max-content;background:#2b2620;color:#fff;font:500 14px/1.45 system-ui,sans-serif;padding:6px 10px;border-radius:8px;box-shadow:0 4px 14px rgba(43,38,32,.25);opacity:0;transition:opacity .15s;pointer-events:none;text-align:left;white-space:normal}.gl-tip.on{opacity:1}@media (prefers-reduced-motion:reduce){.gl-tip{transition:none}}";
  (document.head || document.documentElement).appendChild(st);
  var box = null, cur = null, opened = 0;
  function pop() {
    if (!box) {
      box = document.createElement("div");
      box.className = "gl-tip"; box.id = "gl-tip"; box.setAttribute("role", "tooltip");
      document.body.appendChild(box);
    }
    return box;
  }
  function place(el) {
    var b = pop(), r = el.getBoundingClientRect(), vw = document.documentElement.clientWidth, m = 16;
    b.style.left = "0px"; b.style.top = "0px";
    var w = b.offsetWidth, h = b.offsetHeight;
    var x = Math.min(Math.max(m, r.left + r.width / 2 - w / 2), vw - m - w);
    var y = r.top - h - 8;
    if (y < 8) y = r.bottom + 8;
    b.style.left = Math.max(m, x) + "px"; b.style.top = y + "px";
  }
  function show(el) {
    if (cur && cur !== el) hide();
    var b = pop();
    b.textContent = el.getAttribute("data-tip");
    if (el.hasAttribute("title")) { el.setAttribute("data-t", el.getAttribute("title")); el.removeAttribute("title"); }
    el.setAttribute("aria-describedby", "gl-tip");
    cur = el; opened = Date.now();
    place(el);
    requestAnimationFrame(function () { b.classList.add("on"); });
  }
  function hide() {
    if (!cur) return;
    if (cur.hasAttribute("data-t")) { cur.setAttribute("title", cur.getAttribute("data-t")); cur.removeAttribute("data-t"); }
    cur.removeAttribute("aria-describedby");
    cur = null;
    if (box) box.classList.remove("on");
  }
  var tgt = function (e) { return e.target && e.target.closest ? e.target.closest(".zh[data-tip]") : null; };
  document.addEventListener("click", function (e) {
    var el = tgt(e);
    if (!el) { hide(); return; }
    if (cur === el && Date.now() - opened > 400) hide(); else if (cur !== el) show(el);
  });
  document.addEventListener("focusin", function (e) { var el = tgt(e); if (el) show(el); });
  document.addEventListener("focusout", function (e) { if (tgt(e) === cur) hide(); });
  document.addEventListener("keydown", function (e) {
    if (e.key === "Escape") { hide(); return; }
    var el = tgt(e);
    if (el && (e.key === "Enter" || e.key === " ")) { e.preventDefault(); if (cur === el) hide(); else show(el); }
  });
  window.addEventListener("scroll", function () { if (cur) place(cur); }, { passive: true });
  window.addEventListener("resize", function () { if (cur) place(cur); });
})();
